name: test_library
version: 0.0.1
author: Thierry Bayi <thierrybayi@gmail.com>
description: An example of how to use test_library, a library for educational purposes.
homepage: http://ondart.me/
#dependencies:
#  unittest: any